export const projectErrors = {
  ENTITLEMENT_REQUIRED: { status: 403, message: "Creating projects isn't enabled for this account." },
  OWNED_PROJECT_LIMIT: { status: 422, message: "You've reached your active project limit. Archive a project or ask for a higher limit." },
  OWNER_CANNOT_LEAVE: { status: 409, message: "The project owner can't leave. Archive the project instead." },
  ALREADY_MEMBER: { status: 409, message: "You already have access to this project." },
  COLLABORATOR_LIMIT: { status: 422, message: "This project is full (10 collaborators including the owner)." },
  INVITATION_LIMIT: { status: 409, message: "This project already has the maximum number of pending invitations." },
  NOT_FOUND: { status: 404, message: "This project or invitation is unavailable." },
  KEY_REUSED: { status: 409, message: "This request conflicts with an earlier request." },
  INVALID_INPUT: { status: 400, message: "Check the details and try again." },
  CONFLICT: { status: 409, message: "That change conflicts with current data. Refresh and try again." },
  FORBIDDEN: { status: 403, message: "This action isn't available for your account." },
  UNAVAILABLE: { status: 503, message: "Project access is unavailable. Try again." },
  STALE_ENTITY_VERSION: { status: 409, message: "Someone saved this item first. Compare the saved value, then save again." },
  STALE_DOCUMENT_REVISION: { status: 409, message: "The flow changed. Review the current version and try again." },
  DEPENDENCY_CONFLICT: { status: 422, message: "Review what this deletion removes, then try again." },
  LIMIT_EXCEEDED: { status: 422, message: "This draft has reached a size limit." },
  VERSION_EXHAUSTED: { status: 409, message: "This item can't be changed any further." },
  DRAFT_REPLACED: { status: 409, message: "This draft was replaced. Reload the project." },
  POSITION_CONFLICT: { status: 409, message: "Someone moved this step first. Keep the saved position or apply yours again." },
  STALE_LAYOUT_REVISION: { status: 409, message: "The layout changed. Preview the arrangement again." },
  ARRANGEMENT_PREVIEW_CHANGED: { status: 409, message: "The flow changed since this preview. Preview the arrangement again." },
  UNSUPPORTED_FLOW_FORMAT: { status: 422, message: "Use a supported ScopeRoom flow file." },
  IMPORT_EXPIRED: { status: 409, message: "This import preview expired. Create a new preview." },
  IMPORT_STALE: { status: 409, message: "This import target changed. Create a new preview." },
  IMPORT_PAYLOAD_MISMATCH: { status: 409, message: "This import does not match its preview." },
  AI_BUSY: { status: 409, message: "An AI request is already running. Wait for it to finish, then try again." },
  AI_BUDGET_EXCEEDED: { status: 429, message: "This project owner has used the daily AI request limit. It resets at 00:00 UTC." },
  RATE_LIMITED: { status: 429, message: "Too many AI requests. Wait a minute and try again." },
  EXPORT_REVISION_CHANGED: { status: 409, message: "The saved flow changed. Refresh and prepare the export again." },
} as const;

export type ProjectErrorCode = keyof typeof projectErrors;
